@echo off
echo Starting Backend...
start "Backend" /min java -jar E:\AI_LEARNING\gulvisha-enterprises\backend\gulvisha-backend\target\gulvisha-backend-0.0.1-SNAPSHOT.jar
echo Waiting 10s for backend...
timeout /t 10 /nobreak > nul
echo Starting Frontend...
start "Frontend" /min cmd /c "cd /d E:\AI_LEARNING\gulvisha-enterprises\frontend\gulvisha-frontend && npm run dev"
echo Waiting 5s for frontend...
timeout /t 5 /nobreak > nul
echo.
echo Checking ports...
netstat -an | findstr ":8080 :5173"
echo.
echo Done! Check the minimized windows for server output.
pause
